apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: csv-app.k8s.local
spec:
  kubernetesVersion: 1.29.0
  cloudProvider: aws
  configBase: s3://prateek-documents/kops-state/csv-app.k8s.local
  networking:
    amazonvpc: {}
  subnets:
    - name: ap-south-1a
      type: Public
      zone: ap-south-1a
      cidr: 10.0.0.0/19           
    - name: ap-south-1b
      type: Public
      zone: ap-south-1b
      cidr: 10.0.32.0/19         
    - name: ap-south-1c
      type: Public
      zone: ap-south-1c
      cidr: 10.0.64.0/19           
  networkCIDR: 10.0.0.0/16
  topology:
    masters: public
    nodes: public
  clusterAutoscaler:
    enabled: true
    expander: least-waste
    balanceSimilarNodeGroups: true
    skipNodesWithSystemPods: false
    skipNodesWithLocalStorage: false
    scaleDownDelayAfterAdd: 10m
    scaleDownUnneededTime: 10m